apiVersion: v1
kind: Service
metadata:
  name: new-selector-svc
  namespace: sample-product-staging1
spec:
  ports:
    - name: no-selector-port1
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: no-selector-port2
      port: 8081
      protocol: TCP
      targetPort: 8081
  type: ClusterIP
