apiVersion: v1
kind: Service
metadata:
  name: new-selector-svc
  namespace: sample-product-dev1
spec:
  ports:
    - name: no-selector-port3
      port: 8083
      protocol: TCP
      targetPort: 8083
    - name: no-selector-port4
      port: 8084
      protocol: TCP
      targetPort: 8084
  type: ClusterIP
