apiVersion: v1
kind: Service
metadata:
  name: new-selector-svc1
  namespace: sample-product-dev1
spec:
  ports:
    - name: no-selector-port3
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: no-selector-port4
      port: 8080
      protocol: TCP
      targetPort: 8080
  type: ClusterIP
