apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  name: sample-product-dev2
  namespace: argocd
spec:
  destination:
    name: india
    namespace: default
  project: sample-product
  source:
    path: products/sample-product/manifests/dev2/
    plugin:
      name: argocd-vault-plugin
    repoURL: git@github.com:KrishnaSindhur/clutch-test3
    targetRevision: main
  syncPolicy:
    automated:
      allowEmpty: false
      prune: false
      selfHeal: true
    syncOptions:
      - FailOnSharedResource=true
