apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: krishna-rbac-editor
  namespace: sample-product-krishna
rules:
  - apiGroups:
      - "*"
    resources:
      - "*"
    verbs:
      - create
      - delete
      - update
      - get
      - list
      - watch
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: oidc-krishna-rbac-editor
  namespace: sample-product-krishna
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: krishna-rbac-editor
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: Group
    name: CPaaS-stage-sample-product-editor
